### ISSUE TITLE
Usage with bluebird-co changed

### ISSUE THREAD

**Issue by nemesisqp** [nodeca/event-wire#2]
I'm follow readme and got error 
```
Error: Listener should be the function or generator function
    at Wire.on (D:\PrivateProject\nerve\api-cloud-file\node_modules\event-wire\index.js:419:11)
    at _.forOwn (D:\PrivateProject\nerve\api-cloud-file\server\boot\service.js:14:26)
```
new init seem like this
```javascript
event = require('event-wire')({
    co: require('bluebird-co').co, // <-- this
    p:  require('bluebird')
});
```

**Comment by puzrin** [comment]
You are right, readme needs fix. I can suggest more simple, without `bluebird-co`:

```js
const P = require('bluebird');
const wire = require('event-wire')({
  p: P,
  co: (fn, params) => P.coroutine(fn)(params)
});
```

**Comment by nemesisqp** [comment]
oh thanks.
